from django.urls import path

from .main_map.main import (
    get_map,
    segment_box,
    send_sat_list,
    send_sat_geo,
    send_maxar_list,
    send_maxar_dates,
    send_geo,
    get_sat_dates,
    get_sat_dates_old,
    test,
    object_detection,
    Download,
    ndvi_trends,
    ndvi_progress,
    get_highlights_list,
    get_water_change,
    get_sat_layer,
    get_region_area,
)
from .views import *
from .verify import *
from .auth import *
from .cloud import *
from .logger import *
from .gemini_api_integration import *
from .user_permissions import manage_permissions, update_permissions
import ee
from .geoserver_func import download_and_upload_tif_from_s3


service_account = os.getenv("SERVICE_ACCOUNT")
key_path = "config_files/ee-support-drishti-geoportal-57e96840ceb6.json"
credentials = ee.ServiceAccountCredentials(service_account, key_path)
ee.Initialize(credentials)


urlpatterns = [
    # test url
    path("test/", test, name="test"),
    # auth urls
    path("create-organizations/", create_organizations, name="create_organizations"),
    path("create-member/<int:id>", create_member, name="create_member"),
    path("read-organization/<int:email>", read_organization, name="read_organization"),
    path("read-member/<int:pk>", read_member, name="read_member"),
    path("read-member-one/<int:email>", read_member, name="read_member"),
    path("read_attributes", read_attributes, name="read_attributes"),
    path("update-member/", update_member, name="update_member"),
    path("update-member/<int:id>", update_member_one, name="update_member"),
    path("update-organization/", update_organization, name="update_organization"),
    path("update_attribute", update_attribute, name="update_attribute"),
    path("login/", login_user, name="login"),
    path("sign-up/", sign_up, name="sign-up"),
    path("delete/", delete_member, name="delete_member"),
    path("view-role/<str:id>", view_role, name="view_role"),
    path("create-role/", create_role, name="create_role"),
    path("update-role/", update_role, name="update_role"),
    path("delete-role/", delete_role, name="delete_role"),
    path("delete-organization/", delete_organization, name="delete_organization"),
    path("login-time/<int:id>", login_time, name="login_time"),
    # path("logoutUser", logoutUser, name="logoutUser"),
    path("fetch_projects/<str:email>", fetch_projects, name="fetch_projects"),
    path("fetch-projects-all", fetch_projects_all, name="fetch_projects_all"),
    path("is-session", is_session, name="is_session"),
    path("get-map", get_map, name="get_map"),
    path("segment", segment_box, name="segment"),
    path("object-detection", object_detection, name="object_detection"),
    # maxar urls
    path("maxar-list", send_maxar_list, name="maxar_list"),
    path("maxar-info", send_maxar_dates, name="maxar_dates"),
    path("maxar-geo", send_geo, name="send_geo"),
    # sat data visualisation urls
    path("sat-list/<str:name>", send_sat_list, name="send_sat_list"),
    path("sat-geo/<str:id>", send_sat_geo, name="send_sat_geo"),
    path("get-sat-layer", get_sat_layer, name="get sat layer"),
    path("get-dates", get_sat_dates, name="get_sat_dates"),
    path("get-dates/<str:name>", get_sat_dates_old, name="get_sat_dates"),
    path("get-region-area", get_region_area, name="get_region_area"),
    path("ndvi-trends", ndvi_trends, name="ndvi_trends"),
    path("download", Download, name="download"),
    path("logout", logout, name="logout"),
    path("project-get-layer", admin_get_file, name="admin_get_file"),
    path("project/<str:name>/<int:z>/<int:x>/<int:y>.png", a_tile, name="admin_tiles"),
    path("jeevitnadi/get-image-data/<int:id>", get_image_data, name="get_image_data"),
    path("jeevitnadi/image/<int:id>/<str:name>", serve_image, name="serve_images"),
    path(
        "maxar/<str:type>/<str:dataset>",
        get_highlights_list,
        name="get_highlights_list",
    ),
    path("upload/<str:user_id>", save_file, name="Save user file"),
    path("building-data", get_building_data, name="get_building_data"),
    path("gif", get_gif, name="get_gif"),
    path("water-change", get_water_change, name="Water Change"),
    path("get-taluka/<str:dis>", get_taluka, name="Taluka"),
    path(
        "get-water-body/<str:type_name>/<str:name>",
        get_water_body,
        name="Get_Water_Body",
    ),
    path("clip-list/<str:type_name>/<str:name>", get_clip_list, name="get-clip-list"),
    path("clip-dis-list", get_dis_list, name="get district list"),
    path("clip-list", get_clip_list, name="get-clip-list-no-params"),
    path("ndvi-progress/<str:key>", ndvi_progress, name="NDVI Progress"),
    path("manage-permissions/<str:pk>", manage_permissions, name="manage_permissions"),
    path(
        "update-permissions/<str:user_id>/<str:permission_id>/<str:status>",
        update_permissions,
        name="update_permissions",
    ),
    path("ship-od", get_ship_od, name="get_ship_od"),
    path("verify-user/<str:encoded_id>/", verify_email, name="verify-user"),
    path("resend-email/<str:email>", resend_email, name="resend-email"),
    path("draw-act", draw_activity, name="Draw Activity"),
    path("upload-act", upload_activity, name="Upload Activity"),
    path("remove-layer-act", remove_layer_act, name="remove-layer-act"),
    path("fetch-act/<str:id>/<str:date>", fetch_act, name="fetch-activity"),
    path("fetch-act-view", fetch_act_view, name="fetch activity view"),
    path("send-otp/<str:email>", send_otp, name="send-otp"),
    path("send-otp-key/<str:email>/<str:key>", send_otp_key, name="send-otp"),
    path(
        "send-signup-verification-otp/<str:email>/<str:username>",
        send_signup_verification_otp,
        name="send-signup-verification-otp",
    ),
    path("verify-otp/<str:otp>/<str:key>", verify_otp, name="send-otp"),
    path("reset-password", reset_password, name="reset-password"),
    path("uploads/project", save_files, name="save-files"),
    path("delete-objects", delete_objects, name="delete-objects"),
    path("create-project", create_project, name="create-project"),
    path("delete-project/<str:id>", delete_project, name="delete-project"),
    path("layer-to-pro", layer_to_pro, name="layer-to-pro"),
    path("geo-to-pro", geo_to_pro, name="geo-to-pro"),
    path("fetch-meta/<str:id>", send_metadata, name="fetch-metadata"),
    path("update-project/<str:id>", update_project, name="update-project"),
    path("migrate-project/<str:id>", migrate_project, name="migrate-project"),
    path("fetch-space/<str:id>", fetch_space, name="fetch-space"),
    path("upload-survey", upload_survey, name="upload-survey"),
    path("survey/image/<str:name>", image_serve, name="serve_images"),
    path("s3", download_and_upload_tif_from_s3, name="download_and_upload_tif_from_s3"),
    path("upload_csv", upload_csv, name="upload_csv"),
    path("cloud/<str:id>", cloud, name="cloud"),
    path("deleteCloud/<str:id>", deleteCloud, name="deleteCloud"),
    path("Upload_object", Upload_object, name="put_object"),
    path("Download_object", download_object, name="Download_object"),
    # path("renameCloudFolder",renameCloudFolder,name="renameCloudFolder"),
    path("csrf/", csrf, name="get-csrf"),
    path("createfolder", create_object, name="create_object"),
    path("forest-fire", forest_fire, name="Forest Fire"),
    path(
        "upload-profile-picture/<int:id>",
        upload_profile_picture,
        name="upload_profile_picture",
    ),
    path(
        "get-profile-picture/<int:id>", get_profile_picture, name="get_profile_picture"
    ),
    path(
        "send_organization_request/<int:user_id>/",
        check_organization_exists,
        name="send_organization_request",
    ),
    path("user-requests/<int:user_id>/", get_user_requests, name="user_requests"),
    path(
        "approve-request/<int:notification_id>/action",
        accept_reject_notification,
        name="accept_reject_notification",
    ),
    path("ndvi-change", ndvi_change, name="Ndvi Change"),
    path("get-thres-change", get_thres_change, name="get_thres_change"),
    path("get-lulc", get_lulc, name="get_lulc"),
    path("get-pixel-value", get_pixel_value, name="get pixel value"),
    path("pixel-filter", filter_pixel, name="pixel filter"),
    path("calc-pixel", calc_pixel, name="Raster Calculator"),
    path("get-bands/<str:key>", get_bands, name="get-bands"),
    path("get-bands-add/", get_bands_add, name="get-bands-add"),
    path(
        "create_survey_form/<int:user_id>",
        create_survey_form,
        name="create_survey_form",
    ),
    path("get_survey_forms/<int:user_id>", get_survey_forms, name="get_survey_forms"),
    path("survey_form_submit", survey_form_submit, name="survey_form_submit"),
    path("fetch_emails/<int:id>", fetch_all_emails, name="fetch_emails"),
    path(
        "view_survey_field_data/<str:id>",
        view_survey_field_data,
        name="view_survey_field_data",
    ),
    path("delete_survey/<str:survey_field_id>", delete_survey, name="delete_survey"),
    path(
        "get_survey_data_inputs/<int:survey_id>/",
        get_survey_data_inputs,
        name="get_survey_data_inputs",
    ),
    path(
        "edit_survey_data_inputs/<int:survey_id>/",
        edit_or_add_survey_data_inputs,
        name="edit_or_add_survey_data_inputs",
    ),
    path("surveyfield/<int:survey_id>/", surveyfield, name="survey-data-response"),
    path(
        "view-survey-response/<int:survey_id>/<int:index>",
        surveyResponse,
        name="survey-data-response",
    ),
    path(
        "clear-survey-response/<int:survey_id>/<int:index>",
        clear_survey_response,
        name="clear-survey-response",
    ),
    path(
        "clear-all-survey-response/<str:survey_field_id>",
        clear_all_survey_response,
        name="clear-all-survey-response",
    ),
    path("survey/<int:survey_id>/<str:email>", surveyfield_csv, name="surveyfield_csv"),
    path("upload_image/<int:id>/", upload_image, name="upload_image"),
    path("download_image/<int:id>/", download_image, name="download_image"),
    path("water-change-diff", water_change, name="water-change-diff"),
    path("log/", log_message, name="log_message"),
    path("get_log", get_logs_api, name="get_logs_api"),
    path("delete_log/<int:log_id>", delete_log, name="delete_log"),
    path("sse/updates/<str:id>", get_cache_update, name="get-cache-update"),
    path(
        "all-tables/<str:table>/<str:column>/<str:table2>",
        all_tables,
        name="all-tables",
    ),
    path("table-type/<str:table>", table_type, name="table-type"),
    path("build-buffer", BuildBuffer, name="build-buffer"),
    path("build-result", BuildResult, name="build-result"),
    path("get-sld/<str:id>", sendSld, name="get-sld"),
    path("apply-sld/<str:id>/<str:layer>/<str:style>", applySLD, name="get-sld"),
    path("check-pro/<str:id>/<str:pro_id>", check_project, name="Check Project"),
    path("change-plan/<str:id>", change_plan, name="Change Plan"),
    # feature urls
    path("add-feature/<str:id>", add_feature, name="Add Sidebar Feature"),
    path("get-feature/<str:id>", get_features, name="Get Sidebar Feature"),
    path("delete-feature/<str:id>", del_feature, name="Delete Sidebar Feature"),
    path("get-credit-transaction/<str:id>", get_credit_transactions, name="Get Credit"),
    path(
        "get-credit-sq-km/<str:id>/<str:area>",
        get_credit_sq_km,
        name="get-credit-sq-km",
    ),
    path(
        "update-credit/<str:id>/<str:used_credits>", update_credit, name="update credit"
    ),
    path("send-credit/<str:id>/<str:credit>", send_credit, name="Send Credit"),
    path("add-credit-coupon/<str:id>/<str:key>", add_credit_coupon, name="Send Credit"),
    path("shp-table/<str:id>", save_file_to_db, name="Shp to db"),
    path("uploads/georef", upload_image_georef, name="save-upload_image"),
    path("georef-image", get_georeferenced_image, name="save-upload_image"),
    path(
        "download-georef-image",
        download_georeferenced_image,
        name="download-georef-image",
    ),
    path("convert", save_file_convert, name="Save user file"),
    path("build-nested-structure", get_nested_shp_file_structure, name="build_nested_structure"),
    path("filter-and-save-geojson", visualize_filtered_shp_data, name="visualize_filtered_shp_data"),
    path("save-geojson", save_geojson, name="save_geojson"),
    path("upload-tif-image", upload_tif_image, name="upload_tif_image")
]
