version: '3.8'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/etc/staticfiles
    depends_on:
      - web

  web:
    image: vgt-geo-app
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn -w 4 -b 0.0.0.0:8001 mapshow.wsgi:application --timeout 3600"
    volumes:
      - /home/computervision2/Documents/vgt-geo-web-app-react:/home/code/vgt-app/
    ports:
      - "8001:8001" # Maps internal port 8001 to external port 8001

#   db:
#     image: postgres:15
#     environment:
#       POSTGRES_PASSWORD: portaldb123
#       POSTGRES_USER: vgt_admin
#       POSTGRES_DB: vgt
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/

# volumes:
#   postgres_data:
